/* 
 * Tigerblood
 *
 * IP Reputation Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package swagger

type Reputation struct {

	// the network IP or CIDR
	Ip string `json:"ip,omitempty"`

	// how trustworthy the network is from 0 to 100 inclusive with 100 being more trustworthy
	Reputation int32 `json:"reputation,omitempty"`
}
